title: "Thoughts & Writings"
subtitle: "Random observations and reflections on life, and technology"
author: "Chima Ozonwoye"
description: "To the esteemed reader, these reflections represent my ongoing attempt to understand life, work, and technology - I welcome conversations with those who see things differently."

baseurl: "/portfolio"
url: "https://chimazuruihenine.github.io"

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true